version: '3.8'

services:
  some-postgres:
    image: postgres:16.3
    container_name: some-postgres
    # container_name: spotify-psql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./psqlDbData:/var/lib/postgresql/data
