version: '3.8'

services:
  some-postgres:
    image: postgres:16.3
    container_name: some-postgres
    # container_name: spotify-psql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    volumes:
      - ./psqlDbData:/var/lib/postgresql/data
    networks:
      - postgres-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mahadi.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network
    depends_on:
      - some-postgres

networks:
  postgres-network:
    driver: bridge

volumes:
  pgadmin-data:
