export const data =
  [
    {
      "ts": "2018-07-14T22:36:12Z",
      "username": "mahadi4",
      "platform": "Android OS 8.1.0 API 27 (OnePlus, ONEPLUS A6003)",
      "ms_played": 12491,
      "conn_country": "SE",
      "ip_addr_decrypted": "85.228.229.56",
      "user_agent_decrypted": "unknown",
      "master_metadata_track_name": "Actin Crazy",
      "master_metadata_album_artist_name": "Action Bronson",
      "master_metadata_album_album_name": "Mr. Wonderful",
      "spotify_track_uri": "spotify:track:3clX2NMmjaAHmBjeTSa9vV",
      "episode_name": null,
      "episode_show_name": null,
      "spotify_episode_uri": null,
      "reason_start": "clickrow",
      "reason_end": "endplay",
      "shuffle": false,
      "skipped": null,
      "offline": false,
      "offline_timestamp": 1531607758299,
      "incognito_mode": false
    },
    {
      "ts": "2019-09-20T14:04:37Z",
      "username": "mahadi4",
      "platform": "Android OS 9 API 28 (OnePlus, ONEPLUS A6003)",
      "ms_played": 207365,
      "conn_country": "SE",
      "ip_addr_decrypted": "94.234.39.50",
      "user_agent_decrypted": "unknown",
      "master_metadata_track_name": "Wiley Flow",
      "master_metadata_album_artist_name": "Stormzy",
      "master_metadata_album_album_name": "Wiley Flow",
      "spotify_track_uri": "spotify:track:1Iv4wC88uxeAF7SmQQGx3X",
      "episode_name": null,
      "episode_show_name": null,
      "spotify_episode_uri": null,
      "reason_start": "backbtn",
      "reason_end": "trackdone",
      "shuffle": true,
      "skipped": null,
      "offline": false,
      "offline_timestamp": 1568988071466,
      "incognito_mode": false
    },
    {
      "ts": "2022-04-01T11:52:36Z",
      "username": "mahadi4",
      "platform": "OS X 12.2.1 [x86 8]",
      "ms_played": 47252,
      "conn_country": "SE",
      "ip_addr_decrypted": "92.34.10.171",
      "user_agent_decrypted": "unknown",
      "master_metadata_track_name": "Snow",
      "master_metadata_album_artist_name": "Jetson",
      "master_metadata_album_album_name": "Snow",
      "spotify_track_uri": "spotify:track:4SujiYsB9WKh7lbLNdZyzm",
      "episode_name": null,
      "episode_show_name": null,
      "spotify_episode_uri": null,
      "reason_start": "trackdone",
      "reason_end": "remote",
      "shuffle": true,
      "skipped": null,
      "offline": false,
      "offline_timestamp": 1648813906713,
      "incognito_mode": false
    }
  ]
